// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

func (q *Queries) AdvisoryLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, advisoryLock, lockKey)
	return err
}

const createDeviceSession = `-- name: CreateDeviceSession :one
INSERT INTO device_sessions(id, user_id, refresh_token_hash, device_id, expires_at)
VALUES ($1,$2,$3,$4,$5) RETURNING id, user_id, expires_at, created_at
`

type CreateDeviceSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	DeviceID         string             `json:"device_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CreateDeviceSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDeviceSession(ctx context.Context, arg CreateDeviceSessionParams) (CreateDeviceSessionRow, error) {
	row := q.db.QueryRow(ctx, createDeviceSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceID,
		arg.ExpiresAt,
	)
	var i CreateDeviceSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPhoneUser = `-- name: CreatePhoneUser :one
WITH new_user AS (INSERT INTO users DEFAULT VALUES RETURNING id, status, created_at),
new_identity AS (INSERT INTO auth_identities(user_id, provider, provider_subject) SELECT id, 'phone', $1 FROM new_user)
SELECT id, status, created_at FROM new_user
`

type CreatePhoneUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePhoneUser(ctx context.Context, providerSubject string) (CreatePhoneUserRow, error) {
	row := q.db.QueryRow(ctx, createPhoneUser, providerSubject)
	var i CreatePhoneUserRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT u.id, u.status, u.created_at
FROM users u JOIN auth_identities i ON i.user_id=u.id
WHERE i.provider='phone' AND i.provider_subject=$1
`

type FindUserByPhoneRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindUserByPhone(ctx context.Context, providerSubject string) (FindUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, providerSubject)
	var i FindUserByPhoneRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const isActiveSession = `-- name: IsActiveSession :one
SELECT EXISTS(
  SELECT 1 FROM device_sessions s JOIN users u ON u.id=s.user_id
  WHERE s.id=$1 AND s.user_id=$2 AND s.revoked_at IS NULL
    AND s.expires_at>now() AND u.status='active'
)
`

type IsActiveSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsActiveSession(ctx context.Context, arg IsActiveSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveSession, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockActiveDeviceSession = `-- name: LockActiveDeviceSession :one
SELECT s.id, s.user_id, s.refresh_token_hash, s.device_id, s.expires_at
FROM device_sessions s JOIN users u ON u.id=s.user_id
WHERE s.id=$1 AND s.revoked_at IS NULL AND u.status='active'
FOR UPDATE
`

type LockActiveDeviceSessionRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	DeviceID         string             `json:"device_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) LockActiveDeviceSession(ctx context.Context, id pgtype.UUID) (LockActiveDeviceSessionRow, error) {
	row := q.db.QueryRow(ctx, lockActiveDeviceSession, id)
	var i LockActiveDeviceSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeDeviceSession = `-- name: RevokeDeviceSession :execrows
UPDATE device_sessions SET revoked_at=now() WHERE id=$1 AND revoked_at IS NULL
`

func (q *Queries) RevokeDeviceSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateDeviceSession = `-- name: RotateDeviceSession :exec
UPDATE device_sessions SET refresh_token_hash=$2, rotated_at=now(), expires_at=$3
WHERE id=$1 AND revoked_at IS NULL
`

type RotateDeviceSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RotateDeviceSession(ctx context.Context, arg RotateDeviceSessionParams) error {
	_, err := q.db.Exec(ctx, rotateDeviceSession, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}
