// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConfirmationKind string

const (
	ConfirmationKindExists       ConfirmationKind = "exists"
	ConfirmationKindOpeningHours ConfirmationKind = "opening_hours"
)

func (e *ConfirmationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConfirmationKind(s)
	case string:
		*e = ConfirmationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ConfirmationKind: %T", src)
	}
	return nil
}

type NullConfirmationKind struct {
	ConfirmationKind ConfirmationKind `json:"confirmation_kind"`
	Valid            bool             `json:"valid"` // Valid is true if ConfirmationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConfirmationKind) Scan(value interface{}) error {
	if value == nil {
		ns.ConfirmationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConfirmationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConfirmationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConfirmationKind), nil
}

type ConfirmationResult string

const (
	ConfirmationResultConfirmed ConfirmationResult = "confirmed"
	ConfirmationResultIncorrect ConfirmationResult = "incorrect"
	ConfirmationResultUnknown   ConfirmationResult = "unknown"
)

func (e *ConfirmationResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConfirmationResult(s)
	case string:
		*e = ConfirmationResult(s)
	default:
		return fmt.Errorf("unsupported scan type for ConfirmationResult: %T", src)
	}
	return nil
}

type NullConfirmationResult struct {
	ConfirmationResult ConfirmationResult `json:"confirmation_result"`
	Valid              bool               `json:"valid"` // Valid is true if ConfirmationResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConfirmationResult) Scan(value interface{}) error {
	if value == nil {
		ns.ConfirmationResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConfirmationResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConfirmationResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConfirmationResult), nil
}

type CoordinateSystem string

const (
	CoordinateSystemWgs84 CoordinateSystem = "wgs84"
	CoordinateSystemGcj02 CoordinateSystem = "gcj02"
)

func (e *CoordinateSystem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoordinateSystem(s)
	case string:
		*e = CoordinateSystem(s)
	default:
		return fmt.Errorf("unsupported scan type for CoordinateSystem: %T", src)
	}
	return nil
}

type NullCoordinateSystem struct {
	CoordinateSystem CoordinateSystem `json:"coordinate_system"`
	Valid            bool             `json:"valid"` // Valid is true if CoordinateSystem is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoordinateSystem) Scan(value interface{}) error {
	if value == nil {
		ns.CoordinateSystem, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoordinateSystem.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoordinateSystem) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoordinateSystem), nil
}

type PlaceFeedbackKind string

const (
	PlaceFeedbackKindEntrance      PlaceFeedbackKind = "entrance"
	PlaceFeedbackKindIncorrectInfo PlaceFeedbackKind = "incorrect_info"
)

func (e *PlaceFeedbackKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaceFeedbackKind(s)
	case string:
		*e = PlaceFeedbackKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaceFeedbackKind: %T", src)
	}
	return nil
}

type NullPlaceFeedbackKind struct {
	PlaceFeedbackKind PlaceFeedbackKind `json:"place_feedback_kind"`
	Valid             bool              `json:"valid"` // Valid is true if PlaceFeedbackKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaceFeedbackKind) Scan(value interface{}) error {
	if value == nil {
		ns.PlaceFeedbackKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaceFeedbackKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaceFeedbackKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaceFeedbackKind), nil
}

type AuthIdentity struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DeviceSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	DeviceID         string             `json:"device_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RotatedAt        pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Place struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	CategoryID      pgtype.Text        `json:"category_id"`
	Address         pgtype.Text        `json:"address"`
	CityCode        pgtype.Text        `json:"city_code"`
	DistrictCode    pgtype.Text        `json:"district_code"`
	LocationWgs84   interface{}        `json:"location_wgs84"`
	Gcj02Latitude   float64            `json:"gcj02_latitude"`
	Gcj02Longitude  float64            `json:"gcj02_longitude"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PlaceCategory struct {
	ID          string      `json:"id"`
	DisplayName string      `json:"display_name"`
	ParentID    pgtype.Text `json:"parent_id"`
	SortOrder   int32       `json:"sort_order"`
	Enabled     bool        `json:"enabled"`
}

type PlaceConfirmation struct {
	ID                   pgtype.UUID        `json:"id"`
	PlaceID              pgtype.UUID        `json:"place_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Kind                 ConfirmationKind   `json:"kind"`
	Result               ConfirmationResult `json:"result"`
	ClientIdempotencyKey string             `json:"client_idempotency_key"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PlaceFeedback struct {
	ID                   pgtype.UUID        `json:"id"`
	PlaceID              pgtype.UUID        `json:"place_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Kind                 PlaceFeedbackKind  `json:"kind"`
	Details              string             `json:"details"`
	ClientIdempotencyKey string             `json:"client_idempotency_key"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PlaceOpeningHour struct {
	ID         pgtype.UUID `json:"id"`
	PlaceID    pgtype.UUID `json:"place_id"`
	Weekday    int16       `json:"weekday"`
	OpensAt    pgtype.Time `json:"opens_at"`
	ClosesAt   pgtype.Time `json:"closes_at"`
	Status     string      `json:"status"`
	ValidFrom  pgtype.Date `json:"valid_from"`
	ValidUntil pgtype.Date `json:"valid_until"`
}

type PlaceSource struct {
	ID                  pgtype.UUID        `json:"id"`
	PlaceID             pgtype.UUID        `json:"place_id"`
	Provider            string             `json:"provider"`
	ExternalID          string             `json:"external_id"`
	RawCoordinateSystem CoordinateSystem   `json:"raw_coordinate_system"`
	FetchedAt           pgtype.Timestamptz `json:"fetched_at"`
	Etag                pgtype.Text        `json:"etag"`
}

type ProviderCacheMetadatum struct {
	CacheKey   string             `json:"cache_key"`
	Provider   string             `json:"provider"`
	FetchedAt  pgtype.Timestamptz `json:"fetched_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	StaleUntil pgtype.Timestamptz `json:"stale_until"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
