// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: places.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterializedPlace = `-- name: CreateMaterializedPlace :one
INSERT INTO places(name,category_id,address,city_code,district_code,location_wgs84,gcj02_latitude,gcj02_longitude,source_updated_at)
VALUES($1,NULLIF($2::text,''),$3,$4,$5,ST_SetSRID(ST_MakePoint($6::double precision,$7::double precision),4326)::geography,$8,$9,$10::timestamptz)
RETURNING id
`

type CreateMaterializedPlaceParams struct {
	Name            string             `json:"name"`
	CategoryID      string             `json:"category_id"`
	Address         pgtype.Text        `json:"address"`
	CityCode        pgtype.Text        `json:"city_code"`
	DistrictCode    pgtype.Text        `json:"district_code"`
	Wgs84Longitude  float64            `json:"wgs84_longitude"`
	Wgs84Latitude   float64            `json:"wgs84_latitude"`
	Gcj02Latitude   float64            `json:"gcj02_latitude"`
	Gcj02Longitude  float64            `json:"gcj02_longitude"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
}

func (q *Queries) CreateMaterializedPlace(ctx context.Context, arg CreateMaterializedPlaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMaterializedPlace,
		arg.Name,
		arg.CategoryID,
		arg.Address,
		arg.CityCode,
		arg.DistrictCode,
		arg.Wgs84Longitude,
		arg.Wgs84Latitude,
		arg.Gcj02Latitude,
		arg.Gcj02Longitude,
		arg.SourceUpdatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPlaceSource = `-- name: CreatePlaceSource :exec
INSERT INTO place_sources(place_id,provider,external_id,raw_coordinate_system,fetched_at)
VALUES($1,$2,$3,$4,now())
`

type CreatePlaceSourceParams struct {
	PlaceID             pgtype.UUID      `json:"place_id"`
	Provider            string           `json:"provider"`
	ExternalID          string           `json:"external_id"`
	RawCoordinateSystem CoordinateSystem `json:"raw_coordinate_system"`
}

func (q *Queries) CreatePlaceSource(ctx context.Context, arg CreatePlaceSourceParams) error {
	_, err := q.db.Exec(ctx, createPlaceSource,
		arg.PlaceID,
		arg.Provider,
		arg.ExternalID,
		arg.RawCoordinateSystem,
	)
	return err
}

const findPlaceConfirmationByKey = `-- name: FindPlaceConfirmationByKey :one
SELECT id,place_id,user_id,kind,result,created_at
FROM place_confirmations WHERE user_id=$1 AND client_idempotency_key=$2
`

type FindPlaceConfirmationByKeyParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	ClientIdempotencyKey string      `json:"client_idempotency_key"`
}

type FindPlaceConfirmationByKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	PlaceID   pgtype.UUID        `json:"place_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      ConfirmationKind   `json:"kind"`
	Result    ConfirmationResult `json:"result"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindPlaceConfirmationByKey(ctx context.Context, arg FindPlaceConfirmationByKeyParams) (FindPlaceConfirmationByKeyRow, error) {
	row := q.db.QueryRow(ctx, findPlaceConfirmationByKey, arg.UserID, arg.ClientIdempotencyKey)
	var i FindPlaceConfirmationByKeyRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.UserID,
		&i.Kind,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const findPlaceFeedbackByKey = `-- name: FindPlaceFeedbackByKey :one
SELECT id,place_id,user_id,kind,details,created_at
FROM place_feedbacks WHERE user_id=$1 AND client_idempotency_key=$2
`

type FindPlaceFeedbackByKeyParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	ClientIdempotencyKey string      `json:"client_idempotency_key"`
}

type FindPlaceFeedbackByKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	PlaceID   pgtype.UUID        `json:"place_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      PlaceFeedbackKind  `json:"kind"`
	Details   string             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindPlaceFeedbackByKey(ctx context.Context, arg FindPlaceFeedbackByKeyParams) (FindPlaceFeedbackByKeyRow, error) {
	row := q.db.QueryRow(ctx, findPlaceFeedbackByKey, arg.UserID, arg.ClientIdempotencyKey)
	var i FindPlaceFeedbackByKeyRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.UserID,
		&i.Kind,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const findPlaceSource = `-- name: FindPlaceSource :one
SELECT place_id FROM place_sources
WHERE provider=$1 AND external_id=$2
`

type FindPlaceSourceParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) FindPlaceSource(ctx context.Context, arg FindPlaceSourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findPlaceSource, arg.Provider, arg.ExternalID)
	var place_id pgtype.UUID
	err := row.Scan(&place_id)
	return place_id, err
}

const getPlace = `-- name: GetPlace :one
SELECT id, name, category_id, address, city_code, district_code,
       ST_Y(location_wgs84::geometry)::double precision AS wgs84_latitude,
       ST_X(location_wgs84::geometry)::double precision AS wgs84_longitude,
       gcj02_latitude, gcj02_longitude, source_updated_at, created_at, updated_at
FROM places WHERE id = $1
`

type GetPlaceRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	CategoryID      pgtype.Text        `json:"category_id"`
	Address         pgtype.Text        `json:"address"`
	CityCode        pgtype.Text        `json:"city_code"`
	DistrictCode    pgtype.Text        `json:"district_code"`
	Wgs84Latitude   float64            `json:"wgs84_latitude"`
	Wgs84Longitude  float64            `json:"wgs84_longitude"`
	Gcj02Latitude   float64            `json:"gcj02_latitude"`
	Gcj02Longitude  float64            `json:"gcj02_longitude"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlace(ctx context.Context, id pgtype.UUID) (GetPlaceRow, error) {
	row := q.db.QueryRow(ctx, getPlace, id)
	var i GetPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Address,
		&i.CityCode,
		&i.DistrictCode,
		&i.Wgs84Latitude,
		&i.Wgs84Longitude,
		&i.Gcj02Latitude,
		&i.Gcj02Longitude,
		&i.SourceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlaceConfirmation = `-- name: InsertPlaceConfirmation :one
INSERT INTO place_confirmations(place_id,user_id,kind,result,client_idempotency_key)
VALUES($1,$2,$3,$4,$5)
ON CONFLICT(user_id,client_idempotency_key) DO NOTHING
RETURNING id,place_id,user_id,kind,result,created_at
`

type InsertPlaceConfirmationParams struct {
	PlaceID              pgtype.UUID        `json:"place_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Kind                 ConfirmationKind   `json:"kind"`
	Result               ConfirmationResult `json:"result"`
	ClientIdempotencyKey string             `json:"client_idempotency_key"`
}

type InsertPlaceConfirmationRow struct {
	ID        pgtype.UUID        `json:"id"`
	PlaceID   pgtype.UUID        `json:"place_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      ConfirmationKind   `json:"kind"`
	Result    ConfirmationResult `json:"result"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPlaceConfirmation(ctx context.Context, arg InsertPlaceConfirmationParams) (InsertPlaceConfirmationRow, error) {
	row := q.db.QueryRow(ctx, insertPlaceConfirmation,
		arg.PlaceID,
		arg.UserID,
		arg.Kind,
		arg.Result,
		arg.ClientIdempotencyKey,
	)
	var i InsertPlaceConfirmationRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.UserID,
		&i.Kind,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlaceFeedback = `-- name: InsertPlaceFeedback :one
INSERT INTO place_feedbacks(place_id,user_id,kind,details,client_idempotency_key)
VALUES($1,$2,$3,$4,$5)
ON CONFLICT(user_id,client_idempotency_key) DO NOTHING
RETURNING id,place_id,user_id,kind,details,created_at
`

type InsertPlaceFeedbackParams struct {
	PlaceID              pgtype.UUID       `json:"place_id"`
	UserID               pgtype.UUID       `json:"user_id"`
	Kind                 PlaceFeedbackKind `json:"kind"`
	Details              string            `json:"details"`
	ClientIdempotencyKey string            `json:"client_idempotency_key"`
}

type InsertPlaceFeedbackRow struct {
	ID        pgtype.UUID        `json:"id"`
	PlaceID   pgtype.UUID        `json:"place_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      PlaceFeedbackKind  `json:"kind"`
	Details   string             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPlaceFeedback(ctx context.Context, arg InsertPlaceFeedbackParams) (InsertPlaceFeedbackRow, error) {
	row := q.db.QueryRow(ctx, insertPlaceFeedback,
		arg.PlaceID,
		arg.UserID,
		arg.Kind,
		arg.Details,
		arg.ClientIdempotencyKey,
	)
	var i InsertPlaceFeedbackRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.UserID,
		&i.Kind,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const latestPlaceConfirmations = `-- name: LatestPlaceConfirmations :many
SELECT DISTINCT ON (kind) kind, result, created_at
FROM place_confirmations WHERE place_id = $1
ORDER BY kind, created_at DESC, id DESC
`

type LatestPlaceConfirmationsRow struct {
	Kind      ConfirmationKind   `json:"kind"`
	Result    ConfirmationResult `json:"result"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LatestPlaceConfirmations(ctx context.Context, placeID pgtype.UUID) ([]LatestPlaceConfirmationsRow, error) {
	rows, err := q.db.Query(ctx, latestPlaceConfirmations, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestPlaceConfirmationsRow{}
	for rows.Next() {
		var i LatestPlaceConfirmationsRow
		if err := rows.Scan(&i.Kind, &i.Result, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveConfirmationActor = `-- name: LockActiveConfirmationActor :one
SELECT true AS allowed
FROM device_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.user_id = $2
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.status = 'active'
FOR SHARE OF s, u
`

type LockActiveConfirmationActorParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockActiveConfirmationActor(ctx context.Context, arg LockActiveConfirmationActorParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockActiveConfirmationActor, arg.SessionID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const lockActivePlaceFeedbackActor = `-- name: LockActivePlaceFeedbackActor :one
SELECT true AS allowed
FROM device_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.user_id = $2
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.status = 'active'
FOR SHARE OF s, u
`

type LockActivePlaceFeedbackActorParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockActivePlaceFeedbackActor(ctx context.Context, arg LockActivePlaceFeedbackActorParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockActivePlaceFeedbackActor, arg.SessionID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const nearbyPlaces = `-- name: NearbyPlaces :many
SELECT id, name, category_id, address, city_code, district_code,
       ST_Y(location_wgs84::geometry)::double precision AS wgs84_latitude,
       ST_X(location_wgs84::geometry)::double precision AS wgs84_longitude,
       gcj02_latitude, gcj02_longitude, source_updated_at,
       COALESCE(exists_confirmation.result, 'unknown'::confirmation_result) AS exists_result, exists_confirmation.created_at AS exists_confirmed_at,
       COALESCE(opening_hours_confirmation.result, 'unknown'::confirmation_result) AS opening_hours_result, opening_hours_confirmation.created_at AS opening_hours_confirmed_at,
       ST_Distance(location_wgs84, ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography)::double precision AS distance_meters
FROM places
LEFT JOIN LATERAL (
  SELECT result, created_at FROM place_confirmations
  WHERE place_id = places.id AND kind = 'exists'
  ORDER BY created_at DESC, id DESC LIMIT 1
) AS exists_confirmation ON true
LEFT JOIN LATERAL (
  SELECT result, created_at FROM place_confirmations
  WHERE place_id = places.id AND kind = 'opening_hours'
  ORDER BY created_at DESC, id DESC LIMIT 1
) AS opening_hours_confirmation ON true
WHERE ($3::text IS NULL OR category_id = $3)
  AND ST_DWithin(location_wgs84, ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography, $4::double precision)
ORDER BY distance_meters, id
LIMIT $5
`

type NearbyPlacesParams struct {
	Longitude    float64     `json:"longitude"`
	Latitude     float64     `json:"latitude"`
	CategoryID   pgtype.Text `json:"category_id"`
	RadiusMeters float64     `json:"radius_meters"`
	PageSize     int32       `json:"page_size"`
}

type NearbyPlacesRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	CategoryID              pgtype.Text        `json:"category_id"`
	Address                 pgtype.Text        `json:"address"`
	CityCode                pgtype.Text        `json:"city_code"`
	DistrictCode            pgtype.Text        `json:"district_code"`
	Wgs84Latitude           float64            `json:"wgs84_latitude"`
	Wgs84Longitude          float64            `json:"wgs84_longitude"`
	Gcj02Latitude           float64            `json:"gcj02_latitude"`
	Gcj02Longitude          float64            `json:"gcj02_longitude"`
	SourceUpdatedAt         pgtype.Timestamptz `json:"source_updated_at"`
	ExistsResult            ConfirmationResult `json:"exists_result"`
	ExistsConfirmedAt       pgtype.Timestamptz `json:"exists_confirmed_at"`
	OpeningHoursResult      ConfirmationResult `json:"opening_hours_result"`
	OpeningHoursConfirmedAt pgtype.Timestamptz `json:"opening_hours_confirmed_at"`
	DistanceMeters          float64            `json:"distance_meters"`
}

func (q *Queries) NearbyPlaces(ctx context.Context, arg NearbyPlacesParams) ([]NearbyPlacesRow, error) {
	rows, err := q.db.Query(ctx, nearbyPlaces,
		arg.Longitude,
		arg.Latitude,
		arg.CategoryID,
		arg.RadiusMeters,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NearbyPlacesRow{}
	for rows.Next() {
		var i NearbyPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Address,
			&i.CityCode,
			&i.DistrictCode,
			&i.Wgs84Latitude,
			&i.Wgs84Longitude,
			&i.Gcj02Latitude,
			&i.Gcj02Longitude,
			&i.SourceUpdatedAt,
			&i.ExistsResult,
			&i.ExistsConfirmedAt,
			&i.OpeningHoursResult,
			&i.OpeningHoursConfirmedAt,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placeExists = `-- name: PlaceExists :one
SELECT EXISTS(SELECT 1 FROM places WHERE id = $1)
`

func (q *Queries) PlaceExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, placeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMaterializedPlace = `-- name: UpdateMaterializedPlace :exec
UPDATE places SET name=$1,category_id=NULLIF($2::text,''),address=$3,city_code=$4,district_code=$5,
  location_wgs84=ST_SetSRID(ST_MakePoint($6::double precision,$7::double precision),4326)::geography,
  gcj02_latitude=$8,gcj02_longitude=$9,source_updated_at=$10::timestamptz,updated_at=now()
WHERE id=$11
  AND COALESCE(source_updated_at,'epoch'::timestamptz) <= $10::timestamptz
`

type UpdateMaterializedPlaceParams struct {
	Name            string             `json:"name"`
	CategoryID      string             `json:"category_id"`
	Address         pgtype.Text        `json:"address"`
	CityCode        pgtype.Text        `json:"city_code"`
	DistrictCode    pgtype.Text        `json:"district_code"`
	Wgs84Longitude  float64            `json:"wgs84_longitude"`
	Wgs84Latitude   float64            `json:"wgs84_latitude"`
	Gcj02Latitude   float64            `json:"gcj02_latitude"`
	Gcj02Longitude  float64            `json:"gcj02_longitude"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateMaterializedPlace(ctx context.Context, arg UpdateMaterializedPlaceParams) error {
	_, err := q.db.Exec(ctx, updateMaterializedPlace,
		arg.Name,
		arg.CategoryID,
		arg.Address,
		arg.CityCode,
		arg.DistrictCode,
		arg.Wgs84Longitude,
		arg.Wgs84Latitude,
		arg.Gcj02Latitude,
		arg.Gcj02Longitude,
		arg.SourceUpdatedAt,
		arg.ID,
	)
	return err
}
