// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvisoryLock(ctx context.Context, lockKey string) error
	CreateDeviceSession(ctx context.Context, arg CreateDeviceSessionParams) (CreateDeviceSessionRow, error)
	CreateMaterializedPlace(ctx context.Context, arg CreateMaterializedPlaceParams) (pgtype.UUID, error)
	CreatePhoneUser(ctx context.Context, providerSubject string) (CreatePhoneUserRow, error)
	CreatePlaceSource(ctx context.Context, arg CreatePlaceSourceParams) error
	FindPlaceConfirmationByKey(ctx context.Context, arg FindPlaceConfirmationByKeyParams) (FindPlaceConfirmationByKeyRow, error)
	FindPlaceFeedbackByKey(ctx context.Context, arg FindPlaceFeedbackByKeyParams) (FindPlaceFeedbackByKeyRow, error)
	FindPlaceSource(ctx context.Context, arg FindPlaceSourceParams) (pgtype.UUID, error)
	FindUserByPhone(ctx context.Context, providerSubject string) (FindUserByPhoneRow, error)
	GetPlace(ctx context.Context, id pgtype.UUID) (GetPlaceRow, error)
	InsertPlaceConfirmation(ctx context.Context, arg InsertPlaceConfirmationParams) (InsertPlaceConfirmationRow, error)
	InsertPlaceFeedback(ctx context.Context, arg InsertPlaceFeedbackParams) (InsertPlaceFeedbackRow, error)
	IsActiveSession(ctx context.Context, arg IsActiveSessionParams) (bool, error)
	LatestPlaceConfirmations(ctx context.Context, placeID pgtype.UUID) ([]LatestPlaceConfirmationsRow, error)
	LockActiveConfirmationActor(ctx context.Context, arg LockActiveConfirmationActorParams) (bool, error)
	LockActiveDeviceSession(ctx context.Context, id pgtype.UUID) (LockActiveDeviceSessionRow, error)
	LockActivePlaceFeedbackActor(ctx context.Context, arg LockActivePlaceFeedbackActorParams) (bool, error)
	NearbyPlaces(ctx context.Context, arg NearbyPlacesParams) ([]NearbyPlacesRow, error)
	PlaceExists(ctx context.Context, id pgtype.UUID) (bool, error)
	RevokeDeviceSession(ctx context.Context, id pgtype.UUID) (int64, error)
	RotateDeviceSession(ctx context.Context, arg RotateDeviceSessionParams) error
	UpdateMaterializedPlace(ctx context.Context, arg UpdateMaterializedPlaceParams) error
}

var _ Querier = (*Queries)(nil)
