import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader, Glyph, Page, PageScroll, PrimaryButton, StatusPill } from '../../shared/components/AppUI';
import { COLORS, FONTS, RADIUS } from '../../shared/utils/theme';

type Message = { id: string; text: string; mine: boolean };
export default function ChatComposerScreen({ navigation, route }: any) {
  const group = route.params?.conversationId === 'c2'; const [messages, setMessages] = useState<Message[]>([{ id: 'm1', text: '我找到一个附近停车场，入口在辅路。', mine: false }, { id: 'm2', text: '收到，我正在过去。', mine: true }]); const [draft, setDraft] = useState(''); const [sharing, setSharing] = useState(group);
  const send = () => { const value = draft.trim(); if (!value) return; setMessages((current) => [...current, { id: `${Date.now()}`, text: value, mine: true }]); setDraft(''); };
  return <Page><AppHeader title={group ? '成都周末同行' : '小满'} subtitle={group ? '3 位成员 · 私密群' : '好友'} onBack={() => navigation.goBack()} /><PageScroll><Text style={styles.day}>今天</Text>{messages.map((message) => <View key={message.id} style={[styles.row, message.mine && styles.rowMine]}><View style={[styles.bubble, message.mine && styles.mineBubble]}><Text style={[styles.bubbleText, message.mine && styles.mineText]}>{message.text}</Text></View></View>)}{group ? <View style={styles.share}><View style={styles.shareHead}><Glyph symbol="◎" label="位置共享" color={COLORS.success} /><Text style={styles.shareTitle}>{sharing ? '正在共享实时位置' : '尚未加入位置共享'}</Text><StatusPill label={sharing ? '3 人加入' : '可选加入'} tone={sharing ? 'success' : 'neutral'} /></View><Text style={styles.shareText}>成员可自主加入或退出；发起者退出后，本次位置共享立即结束。</Text><PrimaryButton label={sharing ? '退出位置共享' : '加入位置共享'} variant={sharing ? 'danger' : 'secondary'} onPress={() => setSharing((value) => !value)} style={styles.shareButton} /></View> : null}<View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="输入消息" placeholderTextColor={COLORS.textTertiary} style={styles.input} accessibilityLabel="输入消息" multiline /><Pressable accessibilityRole="button" accessibilityLabel="发送消息" onPress={send} style={[styles.send, !draft.trim() && styles.sendDisabled]}><Text style={styles.sendText}>发送</Text></Pressable></View></PageScroll></Page>;
}
const styles = StyleSheet.create({ day: { ...FONTS.caption, color: COLORS.textTertiary, textAlign: 'center', marginVertical: 12 }, row: { flexDirection: 'row', marginBottom: 10 }, rowMine: { justifyContent: 'flex-end' }, bubble: { maxWidth: '82%', padding: 12, borderRadius: RADIUS.md, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border }, mineBubble: { backgroundColor: COLORS.primary, borderColor: COLORS.primary }, bubbleText: { ...FONTS.body, color: COLORS.text, lineHeight: 22 }, mineText: { color: COLORS.white }, share: { marginTop: 8, padding: 14, backgroundColor: COLORS.successLight, borderRadius: RADIUS.lg }, shareHead: { flexDirection: 'row', alignItems: 'center', gap: 7 }, shareTitle: { ...FONTS.body, color: COLORS.text, fontWeight: '700', flex: 1 }, shareText: { ...FONTS.caption, color: COLORS.textSecondary, lineHeight: 20, marginTop: 8 }, shareButton: { marginTop: 12 }, composer: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, marginTop: 20, paddingLeft: 12, minHeight: 52 }, input: { flex: 1, color: COLORS.text, ...FONTS.body, maxHeight: 100, paddingVertical: 8 }, send: { minHeight: 44, paddingHorizontal: 14, justifyContent: 'center' }, sendDisabled: { opacity: .45 }, sendText: { ...FONTS.caption, color: COLORS.primary, fontWeight: '700' } });
