import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader, Chip, Page, PageScroll, PrimaryButton, Segment } from '../../shared/components/AppUI';
import { COLORS, FONTS, RADIUS, SPACING } from '../../shared/utils/theme';

function Input({ label, value, onChangeText, placeholder, multiline, error }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; multiline?: boolean; error?: string }) {
  return <View style={styles.inputGroup}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={COLORS.textTertiary} multiline={multiline} textAlignVertical={multiline ? 'top' : 'center'} style={[styles.input, multiline && styles.textarea, error && styles.inputError]} accessibilityLabel={label} />{error ? <Text style={styles.error}>{error}</Text> : null}</View>;
}

export function CreatePostComposerScreen({ navigation }: any) {
  const [kind, setKind] = useState('地点标注'); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [error, setError] = useState('');
  const submit = () => { if (!title.trim() || !body.trim()) { setError('请填写标题和内容说明。'); return; } navigation.navigate('ModerationStatus', { type: kind }); };
  const publicMarker = kind === '地点标注';
  return <Page><AppHeader title="发布" onBack={() => navigation.goBack()} /><PageScroll><Segment options={['地点标注', '旅行讨论', '旅行计划']} value={kind} onChange={(value) => { setKind(value); setError(''); }} /><View style={styles.guide}><Text style={styles.guideTitle}>{publicMarker ? '公开地点标注会经过两条审核流程' : '发布前会进行基础内容审核'}</Text><Text style={styles.guideText}>{publicMarker ? '论坛内容审核与地点公开审核互不替代。公开标注需补充文字说明和地点照片。' : '请只发布旅行相关、真实且不泄露同行人隐私的内容。'}</Text></View><Input label="标题 *" value={title} onChangeText={setTitle} placeholder="用一句话说清楚内容" /><Input label="内容说明 *" value={body} onChangeText={setBody} placeholder="路线、时间、注意事项或真实体验" multiline />{publicMarker ? <><Input label="关联地点 *" value="" onChangeText={() => undefined} placeholder="点击后从地图选择（接口接入前展示）" /><View style={styles.photo}><Text style={styles.photoTitle}>添加地点照片 *</Text><Text style={styles.photoText}>正式接入后会读取地点与时间证明，用于审核。</Text></View></> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label="提交审核" onPress={submit} /></PageScroll></Page>;
}

export function CreateMarkerComposerScreen({ navigation }: any) {
  const [name, setName] = useState(''); const [location, setLocation] = useState(''); const [scope, setScope] = useState('仅自己'); const [error, setError] = useState('');
  const submit = () => { if (!name.trim() || !location.trim()) { setError('名称和定位点为必填项。'); return; } if (scope === '公开到论坛') { navigation.navigate('ModerationStatus', { type: '地点标注' }); return; } navigation.goBack(); };
  return <Page><AppHeader title="新建标注" onBack={() => navigation.goBack()} /><PageScroll><View style={styles.mapPicker}><Text style={styles.mapSymbol}>⌖</Text><Text style={styles.mapPickerTitle}>选择定位点</Text><Text style={styles.mapPickerText}>可在地图服务接入后拖动标记或搜索地点。</Text></View><Input label="名称 *" value={name} onChangeText={setName} placeholder="例如：安静的观景平台" /><Input label="定位点 *" value={location} onChangeText={setLocation} placeholder="输入地点、地址或经纬度" /><Text style={styles.label}>可见范围</Text><View style={styles.scope}>{['仅自己', '指定好友', '全部好友', '公开到论坛'].map((item) => <Chip key={item} label={item} selected={scope === item} onPress={() => setScope(item)} />)}</View>{scope === '公开到论坛' ? <View style={styles.warning}><Text style={styles.warningTitle}>公开前需要补充描述与照片</Text><Text style={styles.warningText}>照片应保留地点与时间证明；内容审核通过不代表自动进入公共地图。</Text></View> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={scope === '公开到论坛' ? '提交审核' : '保存私密标注'} onPress={submit} /></PageScroll></Page>;
}

export function PlanComposerScreen({ navigation, route }: any) {
  const ai = route.params?.ai; const [destination, setDestination] = useState(''); const [days, setDays] = useState(''); const [preference, setPreference] = useState(''); const [error, setError] = useState('');
  const submit = () => { if (!destination.trim() || !days.trim()) { setError('请填写目的地和天数。'); return; } navigation.navigate('PlanDetail', { planId: 'plan-1', draftTitle: `${destination} ${days} 天游` }); };
  return <Page><AppHeader title={ai ? 'AI 草拟计划' : '新建旅行计划'} onBack={() => navigation.goBack()} /><PageScroll><View style={styles.guide}><Text style={styles.guideTitle}>{ai ? '生成可编辑草稿' : '将地点组织成可执行行程'}</Text><Text style={styles.guideText}>{ai ? 'AI 仅生成草稿，不会自动发布或覆盖你的修改。' : '计划默认仅自己可见，可从地图、收藏、标注和社区加入地点。'}</Text></View><Input label="目的地 *" value={destination} onChangeText={setDestination} placeholder="例如：成都" /><Input label="天数 *" value={days} onChangeText={setDays} placeholder="例如：3" /><Input label="偏好（选填）" value={preference} onChangeText={setPreference} placeholder="慢游、美食、亲子、自驾补给等" multiline />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={ai ? '生成可编辑草稿' : '创建计划'} onPress={submit} /></PageScroll></Page>;
}

const styles = StyleSheet.create({ guide: { backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.lg, padding: 16, marginTop: 18 }, guideTitle: { ...FONTS.body, color: COLORS.text, fontWeight: '700' }, guideText: { ...FONTS.caption, color: COLORS.textSecondary, lineHeight: 20, marginTop: 5 }, inputGroup: { marginTop: 14 }, label: { ...FONTS.caption, color: COLORS.textSecondary, fontWeight: '700', marginBottom: 7 }, input: { minHeight: 48, paddingHorizontal: 12, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.white, color: COLORS.text, ...FONTS.body }, textarea: { minHeight: 112, paddingTop: 12 }, inputError: { borderColor: COLORS.danger }, error: { ...FONTS.caption, color: COLORS.danger, marginTop: 7 }, photo: { marginTop: 14, padding: 16, borderWidth: 1, borderColor: COLORS.border, borderStyle: 'dashed', borderRadius: RADIUS.md, backgroundColor: COLORS.white }, photoTitle: { ...FONTS.body, color: COLORS.text, fontWeight: '700' }, photoText: { ...FONTS.caption, color: COLORS.textSecondary, marginTop: 4, lineHeight: 20 }, mapPicker: { minHeight: 144, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E8F0EC', borderRadius: RADIUS.lg }, mapSymbol: { fontSize: 32, color: COLORS.primary }, mapPickerTitle: { ...FONTS.body, color: COLORS.text, fontWeight: '700', marginTop: 8 }, mapPickerText: { ...FONTS.caption, color: COLORS.textSecondary, marginTop: 4 }, scope: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 }, warning: { backgroundColor: COLORS.warningLight, borderRadius: RADIUS.md, padding: 14, marginTop: 12 }, warningTitle: { ...FONTS.body, color: COLORS.warning, fontWeight: '700' }, warningText: { ...FONTS.caption, color: COLORS.textSecondary, lineHeight: 20, marginTop: 5 } });
