import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { places } from '../demoData';
import type { TravelMode } from '../types';
import { AppHeader, Chip, Glyph, Page, PrimaryButton, StatusPill } from '../../shared/components/AppUI';
import { COLORS, FONTS, RADIUS, SPACING } from '../../shared/utils/theme';

const modes: { id: TravelMode; label: string; symbol: string; eta: string }[] = [{ id: 'walk', label: '步行', symbol: '◌', eta: '12 分钟' }, { id: 'ride', label: '骑行', symbol: '⌁', eta: '5 分钟' }, { id: 'drive', label: '驾车', symbol: '▱', eta: '4 分钟' }, { id: 'transit', label: '公交地铁', symbol: '≋', eta: '18 分钟' }, { id: 'taxi', label: '打车', symbol: '◒', eta: '约 3 分钟到车' }];
export default function NavigationScreen({ navigation, route }: any) {
  const [mode, setMode] = useState<TravelMode>('walk'); const place = places.find((item) => item.id === route.params?.placeId) || places[0]; const selected = modes.find((item) => item.id === mode)!;
  return <Page><AppHeader title="选择出行方式" onBack={() => navigation.goBack()} /><View style={styles.map}><View style={styles.routeLine} /><View style={styles.start}><Glyph symbol="◎" label="当前位置" color={COLORS.white} /></View><View style={styles.end}><Glyph symbol="⌖" label="目的地" color={COLORS.white} /></View>{mode === 'drive' ? <View style={styles.driveHint}><Text style={styles.driveMain}>前方 280 米靠右行驶</Text><Text style={styles.driveSub}>进入体育东路</Text></View> : null}</View><View style={styles.panel}><Text style={styles.destination}>前往 {place.name}</Text><Text style={styles.address}>{place.address}</Text><View style={styles.modes}>{modes.map((item) => <Chip key={item.id} label={`${item.symbol} ${item.label}`} selected={mode === item.id} onPress={() => setMode(item.id)} />)}</View><View style={styles.routeCard}><View><Text style={styles.eta}>{selected.eta}</Text><Text style={styles.routeMeta}>{mode === 'taxi' ? '将跳转第三方叫车服务，不创建平台订单' : '推荐路线 · 约 1.2 公里'}</Text></View><StatusPill label={mode === 'drive' ? '驾驶模式' : '推荐'} tone="primary" /></View>{mode === 'taxi' ? <PrimaryButton label="选择叫车服务" onPress={() => navigation.navigate('ExternalMap', { type: 'taxi' })} /> : <PrimaryButton label={mode === 'drive' ? '进入驾驶模式' : '开始导航'} onPress={() => navigation.navigate('DrivingMode', { mode, placeId: place.id })} />}</View></Page>;
}
export function DrivingModeScreen({ navigation, route }: any) { const driving = route.params?.mode === 'drive'; return <View style={styles.driving}><Text style={styles.drivingTop}>{driving ? '沿途 · 驾驶模式' : '沿途 · 导航中'}</Text><Text style={styles.drivingInstruction}>{driving ? '前方 280 米靠右行驶' : '沿路向前，目的地在右侧'}</Text><Text style={styles.drivingRoad}>{driving ? '体育东路' : '步行约 1.2 公里'}</Text><View style={styles.drivingFooter}><Text style={styles.drivingEta}>预计 {driving ? '4' : '12'} 分钟到达</Text><PrimaryButton label="结束导航" variant="secondary" onPress={() => navigation.popToTop()} /></View></View>; }
export function ExternalMapScreen({ navigation }: any) { return <Page><AppHeader title="外部服务" onBack={() => navigation.goBack()} /><View style={styles.external}><Glyph symbol="↗" label="外部服务跳转" size={36} color={COLORS.primary} /><Text style={styles.externalTitle}>即将跳转第三方服务</Text><Text style={styles.externalText}>首发仅提供跳转入口。出行订单、支付和售后由第三方服务处理。</Text><PrimaryButton label="继续" onPress={() => navigation.goBack()} style={styles.externalButton} /></View></Page>; }
const styles = StyleSheet.create({ map: { height: 270, backgroundColor: '#E8F0EC', overflow: 'hidden' }, routeLine: { position: 'absolute', width: 420, height: 8, borderRadius: 8, backgroundColor: COLORS.primary, transform: [{ rotate: '-21deg' }], top: 145, left: -15 }, start: { position: 'absolute', top: 192, left: 70, width: 36, height: 36, borderRadius: 18, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center' }, end: { position: 'absolute', top: 70, right: 80, width: 42, height: 42, borderRadius: 21, backgroundColor: COLORS.success, justifyContent: 'center', alignItems: 'center' }, driveHint: { position: 'absolute', top: 24, left: 16, right: 16, padding: 14, backgroundColor: COLORS.primary, borderRadius: RADIUS.lg }, driveMain: { ...FONTS.titleMedium, color: COLORS.white }, driveSub: { ...FONTS.caption, color: '#DDEBFF', marginTop: 3 }, panel: { flex: 1, backgroundColor: COLORS.white, marginTop: -20, borderTopLeftRadius: RADIUS.xl, borderTopRightRadius: RADIUS.xl, padding: SPACING.lg }, destination: { ...FONTS.body, color: COLORS.text, fontWeight: '700' }, address: { ...FONTS.caption, color: COLORS.textSecondary, marginTop: 4 }, modes: { flexDirection: 'row', marginTop: 16 }, routeCard: { marginVertical: 16, padding: SPACING.lg, borderRadius: RADIUS.lg, backgroundColor: COLORS.primaryLight, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eta: { ...FONTS.titleMedium, color: COLORS.text }, routeMeta: { ...FONTS.caption, color: COLORS.textSecondary, marginTop: 4 }, driving: { flex: 1, backgroundColor: '#102722', padding: 22, justifyContent: 'space-between' }, drivingTop: { ...FONTS.body, color: '#BED0CB', fontWeight: '700' }, drivingInstruction: { fontSize: 34, lineHeight: 46, fontWeight: '700', color: COLORS.white }, drivingRoad: { ...FONTS.titleMedium, color: '#BCE1D9', marginTop: -160 }, drivingFooter: { gap: 14 }, drivingEta: { ...FONTS.body, color: COLORS.white, textAlign: 'center' }, external: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 }, externalTitle: { ...FONTS.titleMedium, color: COLORS.text, marginTop: 18 }, externalText: { ...FONTS.body, color: COLORS.textSecondary, lineHeight: 24, textAlign: 'center', marginTop: 8 }, externalButton: { alignSelf: 'stretch', marginTop: 28 }, });
